src/main/java/com/crowdin/client/core/http/impl/json/FileExportOptionsDeserializer.java
src/test/java/com/crowdin/client/sourcefiles/SourceFilesApiTest.java
src/test/resources/api/sourcefiles/listFiles.json

Otherwise it would fail to deserialise the file contents by using the
incorrect export options class (`GeneralFileExportOptions` instead of
`PropertyFileExportOptions`).

Check for escapeQuotes when deserialising files

---

src/main/java/com/crowdin/client/translations/model/BuildProjectTranslationRequest.java
src/main/java/com/crowdin/client/translations/model/CharTransformation.java
src/main/java/com/crowdin/client/translations/model/CrowdinTranslationCraeteProjectPseudoBuildForm.java
src/main/java/com/crowdin/client/translations/model/CrowdinTranslationCreateProjectBuildForm.java
src/test/java/com/crowdin/client/translations/TranslationsApiTest.java
src/test/resources/api/translations/pseudoBuildProjectRequest.json

Add missing options from [Build Project Translations](https://support.crowdin.com/api/v2/#tag/Translations/paths/~1projects~1{projectId}~1translations~1builds/post)
(API for enterprise [here](https://support.crowdin.com/enterprise/api/#operation/api.projects.translations.builds.post))

Add non-enterprise options to BuildProjectTranslationRequest

---

src/main/java/com/crowdin/client/tasks/model/CrowdinVendorManualTaskCreateFormRequest.java

- Added Request Body Schema extending the `AddTaskRequest` class to provide the support for `CrowdinVendorManualTaskCreateForm`
- Resolves #107

CrowdinVendorManualTaskCreateForm Support - Tasks Post API

---

src/main/java/com/crowdin/client/translations/model/CrowdinTranslationCreateProjectPseudoBuildForm.java
src/test/java/com/crowdin/client/translations/TranslationsApiTest.java

I'm hoping to deprecate `CrowdinTranslationCraeteProjectPseudoBuildForm` in favor of `CrowdinTranslationCreateProjectPseudoBuildForm`
I'm not sure what the deprecation policy is for this repository, but it does appear that this repository is willing to use `@Deprecated`

spelling: create [API]

---

src/main/java/com/crowdin/client/core/http/impl/json/FileImportOptionsDeserializer.java
src/main/java/com/crowdin/client/sourcefiles/model/DocxFileImportOptions.java
src/test/java/com/crowdin/client/sourcefiles/SourceFilesApiTest.java
src/test/resources/api/sourcefiles/listFiles.json

Add support for docx file import options.
Part of #119.
---
I think this actually addresses the issue but not linking in case you notice that something is not done.
Both `Add File` and `Update or Restore File` use the same base class `ImportOptions` in the request and response.
The `Edit File` is using a `String` for the `path` parameter not an `Enum`.

Add Docx File Import Options

---

src/main/java/com/crowdin/client/core/http/impl/json/JacksonJsonTransformer.java
src/test/java/com/crowdin/client/bundles/BundlesApiTest.java
src/test/java/com/crowdin/client/glossaries/GlossariesApiTest.java
src/test/java/com/crowdin/client/reports/ReportsApiTest.java
src/test/java/com/crowdin/client/screenshots/ScreenshotsApiTest.java
src/test/java/com/crowdin/client/sourcefiles/SourceFilesApiTest.java
src/test/java/com/crowdin/client/tasks/TasksApiTest.java

Fixes: #132 
According to Java documentation of [SimpleDateFormat ](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#timezone)there is wrong pattern of Date of JacksonJsonTransformer in TimeZone part. Fix is simple, it's need to change TimeZone representation from ` +hh:mm `  to ` XXX ` as it is written in docs.

Fix: Wrong Date pattern in JacksonJsonTransformer.java

---

README.md
build.gradle
src/main/java/com/crowdin/client/screenshots/model/AddScreenshotRequest.java
src/test/java/com/crowdin/client/screenshots/ScreenshotsApiTest.java
src/test/resources/api/screenshots/addScreenshotRequest.json

Currently, the API supports more params compared to what's present in the java client request.
This PR adds the missing params to `AddScreenshotRequest`:
- fileId
- branchId
- directoryId

Add missing params to AddScreenshotRequest

---

src/main/java/com/crowdin/client/tasks/TasksApi.java
src/main/java/com/crowdin/client/tasks/model/AddTaskSettingsTemplateRequest.java
src/main/java/com/crowdin/client/tasks/model/LanguageReference.java
src/main/java/com/crowdin/client/tasks/model/TaskSettingsTemplate.java
src/main/java/com/crowdin/client/tasks/model/TaskSettingsTemplateConfig.java
src/main/java/com/crowdin/client/tasks/model/TaskSettingsTemplateResponseList.java
src/main/java/com/crowdin/client/tasks/model/TaskSettingsTemplateResponseObject.java
src/test/java/com/crowdin/client/tasks/TaskSettingsTemplatesApiTest.java
src/test/resources/api/tasks/settings-templates/addTaskSettingsTemplateRequest.json
src/test/resources/api/tasks/settings-templates/commonResponses_single.json
src/test/resources/api/tasks/settings-templates/editTaskSettingsTemplateRequest.json
src/test/resources/api/tasks/settings-templates/listTaskSettingsTemplatesResponse.json

feat(api): add Task Settings Templates API + tests

---

src/main/java/com/crowdin/client/sourcefiles/model/HtmlFileImportOptions.java
src/main/java/com/crowdin/client/sourcefiles/model/HtmlWithFrontMatterFileImportOptions.java
src/main/java/com/crowdin/client/sourcefiles/model/MdxV1FileImportOptions.java

feat(api): source files: add more ImportOptions models

---

src/main/java/com/crowdin/client/sourcestrings/SourceStringsApi.java
src/main/java/com/crowdin/client/sourcestrings/model/SourceStringForm.java
src/test/java/com/crowdin/client/sourcestrings/SourceStringsApiTest.java
src/test/resources/api/strings/stringBatchOperationsRequest.json

feat(api): add String Batch Operations API support

---

.github/workflows/bump-version.yml
.release-it.json

Using the [release-it](https://www.npmjs.com/package/release-it) CLI.
Based on the reusable workflow [crowdin/.github/.github/workflows/bump-version.yml](https://github.com/crowdin/.github/blob/main/.github/workflows/bump-version.yml).

ci: automated versioning

---

src/main/java/com/crowdin/client/bundles/BundlesApi.java
src/main/java/com/crowdin/client/bundles/model/AddBundleRequest.java
src/main/java/com/crowdin/client/bundles/model/Bundle.java
src/test/java/com/crowdin/client/bundles/BundlesApiTest.java
src/test/resources/api/bundles/addBundleRequest.json
src/test/resources/api/bundles/bundle.json
src/test/resources/api/bundles/editBundle.json

feat(api): Bundles API: add the includeProjectSourceLanguage property

---

src/main/java/com/crowdin/client/sourcefiles/model/ExportQuotes.java
src/test/java/com/crowdin/client/core/http/EnumSerializationTest.java
src/test/resources/api/sourcefiles/listFiles.json

This is to showcase the issue. Should be fixed within the current branch
Related to the #178

fix: exportQuotes deserialization

---

src/main/java/com/crowdin/client/translations/model/ApplyPreTranslationRequest.java
src/main/java/com/crowdin/client/translations/model/PreTranslationStatus.java
src/test/java/com/crowdin/client/translations/TranslationsApiTest.java
src/test/resources/api/translations/preTranslationRequest.json
src/test/resources/api/translations/preTranslationStatus.json

feat(api): Pre-Translations: add Label IDs support

---

src/main/java/com/crowdin/client/translations/model/ApplyPreTranslationRequest.java
src/main/java/com/crowdin/client/translations/model/ApplyPreTranslationStringsBasedRequest.java
src/main/java/com/crowdin/client/translations/model/PreTranslationStatus.java
src/main/java/com/crowdin/client/translations/model/UploadTranslationsRequest.java

This change resolves issue #229 by removing the deprecated `markAddedTranslationsAsDone` parameter from the API, which should be removed from the codebase.

fix: removed the `markAddedTranslationsAsDone` parameter

---

src/main/java/com/crowdin/client/reports/model/CostEstimateFuzzyModeGenerateReportRequest.java
src/main/java/com/crowdin/client/reports/model/Mode.java
src/main/java/com/crowdin/client/reports/model/ReportStatusResponseObject.java
src/main/java/com/crowdin/client/reports/model/TranslationCostFuzzyModeGenerateReportRequest.java
src/main/java/com/crowdin/client/reports/model/TranslationCostGenerateReportRequest.java
src/test/java/com/crowdin/client/reports/model/CostEstimateFuzzyModeGenerateReportRequestTest.java
src/test/java/com/crowdin/client/reports/model/GroupingParameterTest.java
src/test/java/com/crowdin/client/reports/model/LabelIncludeTypeTest.java
src/test/java/com/crowdin/client/reports/model/MatchTypeTest.java
src/test/java/com/crowdin/client/reports/model/Reports2FormatTest.java
src/test/java/com/crowdin/client/reports/model/TranslationCostGenerateReportRequestTest.java

Added more unit tests to improve 'report' package code coverage.
Code coverege of 'report' package is 94%

test: improve 'report' package code coverage

---

src/main/java/com/crowdin/client/reports/ReportsApi.java
src/main/java/com/crowdin/client/reports/model/ExportReportRequest.java
src/main/java/com/crowdin/client/reports/model/ReportArchive.java
src/main/java/com/crowdin/client/reports/model/ReportArchiveList.java
src/main/java/com/crowdin/client/reports/model/ReportArchiveResponseObject.java
src/test/java/com/crowdin/client/reports/ReportsApiTest.java
src/test/resources/api/reports/exportReportArchiveReques.json
src/test/resources/api/reports/listReportArchives.json
src/test/resources/api/reports/reportArchive.json

Implemented new endpoints in the Crowdin API for enhanced functionality that allows you to see the history of your reports.
Issue:[#241 ](https://github.com/crowdin/crowdin-api-client-java/issues/241)

feat: add new Report Archives API endpoints

---

src/main/java/com/crowdin/client/screenshots/ScreenshotsApi.java
src/test/java/com/crowdin/client/screenshots/ScreenshotsApiTest.java

I have carefully reviewed the documentation and have added the `stringIds`, `labelIds`, and `excludeLabelIds` parameters to the `ScreenshotsApi.listScreenshots` method. Additionally, I have marked the `stringId` parameter as deprecated.

feat: Screenshots APIs: add the stringIds parameter support

---

src/main/java/com/crowdin/client/core/http/exceptions/HttpBatchBadRequestException.java
src/main/java/com/crowdin/client/core/http/impl/json/CrowdinApiExceptionDeserializer.java
src/test/java/com/crowdin/client/core/http/impl/json/CrowdinApiExceptionDeserializerTest.java
src/test/java/com/crowdin/client/sourcestrings/SourceStringsApiTest.java
src/test/resources/api/core/batchErrorsResponse.json
src/test/resources/api/strings/stringBatchOperationsErrorRequest.json

fix: batch error response processing

---

src/main/java/com/crowdin/client/projectsgroups/model/EnterpriseProjectRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/FilesBasedProjectRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/Project.java
src/main/java/com/crowdin/client/projectsgroups/model/StringsBasedProjectRequest.java

In the request and response parameters of the add project, edit project, and get project interfaces, the newly added defaultTmId and defaultGlossaryId have been added to support the latest methods.

feat: add support for defaultTmId and defaultGlossaryId

---

src/main/java/com/crowdin/client/webhooks/model/Event.java
src/test/java/com/crowdin/client/webhooks/WebhooksApiTest.java
src/test/java/com/crowdin/client/webhooks/WebhooksModelTest.java
src/test/resources/api/webhooks/addWebhookRequestRawEvent.json
src/test/resources/api/webhooks/webhookRawEvent.json

Looks like issue #224 is related to bunch of events that have composite names in their String representation, like 'stringComment.created' or ''task.statusChanged". When converted back to String from enum instance it becomes "stringcomment.created" which no longer matches the original spelling of the event's name.
The provided solution adds ability to specify String representation for enum instance where it's necessary for further conversions.

fix: Event 'from' not working with 'addWebhook'

---

src/main/java/com/crowdin/client/sourcestrings/model/UploadStringsProgress.java
src/main/java/com/crowdin/client/sourcestrings/model/UploadStringsRequest.java
src/test/java/com/crowdin/client/sourcestrings/SourceStringsApiTest.java
src/test/java/com/crowdin/client/sourcestrings/model/UploadStringsRequestTest.java
src/test/resources/api/strings/uploadStrings.json
src/test/resources/api/strings/uploadStringsReq.json

* Added `updateOption` field to strings upload request and progress response according to API Reference docs.
* Covered logic with tests.
Covers #260.

feat: add updateOption field to UploadStringsRequest

---

src/main/java/com/crowdin/client/translations/TranslationsApi.java
src/main/java/com/crowdin/client/translations/model/PreTranslation.java
src/main/java/com/crowdin/client/translations/model/PreTranslationResponseList.java
src/main/java/com/crowdin/client/translations/model/PreTranslationResponseObject.java
src/test/java/com/crowdin/client/translations/TranslationsApiTest.java
src/test/resources/api/translations/editPreTranslationRequest.json
src/test/resources/api/translations/editPreTranslationResponse.json
src/test/resources/api/translations/listPreTranslations.json

Added methods for new pre-translation API endpoints:
* listPreTranslations for [List Pre-Translations](https://support.crowdin.com/developer/api/v2/#tag/Translations/operation/api.projects.pre-translations.getMany)
* editPreTranslation for [Edit Pre-Translation](https://support.crowdin.com/developer/api/v2/#tag/Translations/operation/api.projects.pre-translations.patch)
Closes #266

feat: add support for the list and edit pre-translation API endpoints

---

src/main/java/com/crowdin/client/ai/AIApi.java
src/main/java/com/crowdin/client/ai/model/AiSetting.java
src/main/java/com/crowdin/client/ai/model/AiSettingResponse.java
src/test/java/com/crowdin/client/ai/AIApiTest.java
src/test/resources/api/ai/editAiSettingRequest.json
src/test/resources/api/ai/getAiSettingResponse.json

**Summary:**
- Added methods for AI setting methods for.
- Fixing issue: https://github.com/crowdin/crowdin-api-client-java/issues/274
- reference: https://support.crowdin.com/developer/api/v2/#tag/AI/operation/api.users.ai.settings.get.

feat: Add AI Setting Methods

---

CONTRIBUTING.md

docs: Update Getting Started Section
- Updated the "Getting Started" section to clarify the setup process.
- Added notes on the required API token and organization ID for authentication.
- Included specific instructions for Maven and Gradle build commands.
- Mentioned the ability to customize HTTP timeouts using ClientConfig.

docs: Getting Started Section added

---

src/main/java/com/crowdin/client/reports/ReportsApi.java
src/test/java/com/crowdin/client/reports/ReportsApiTest.java
src/test/resources/api/reports/addUserReportSettingsTemplate.json
src/test/resources/api/reports/editUserReportSettingsTemplate.json
src/test/resources/api/reports/listUserReportSettingsTemplate.json
src/test/resources/api/reports/userReportSettingsTemplate.json

This introduces support for the `User Report Settings Templates` endpoints. For implementation I focused on reusing the existing `Report Settings Templates` logic and made the necessary adjustments to handle the user-specific endpoints.
**Changes**
- Added the methods to support the `User Report Settings Templates` endpoints (`List`, `Add`, `Get`, `Delete`, `Edit`).
- Reused logic from the existing `Report Settings Template` code, with changes to the `URLs` and `parameters`.
- Created 4 new `JSON` files for the `User Report Settings Templates`, structured after the existing `Report Settings Template` files.
- Added test methods to ensure the new functionality works as expected.
**Testing**
- All tests for the added methods pass successfully.
- In case of `Add` test method, I set (in the …

feat: Add user report endpoints support

---

src/main/java/com/crowdin/client/stringtranslations/StringTranslationsApi.java
src/test/java/com/crowdin/client/stringtranslations/StringTranslationsApiTest.java

<details><summary>Summary</summary>
<p>
Introduces support for the `Remove String Approvals` endpoint and refactors `deleteStringTranslations` method and its corresponding test for better parameter handling.
</p>
</details> 
**Changes**
- Added new method to support the `Remove String Approvals` endpoint.
- Updated the newly added method (`removeStringApprovals`) and the existing one (`deleteStringTranslations`) to fix request type and parameters requirements.
- Changed `HTTP` method from `GET` to `DELETE` for deletion operations.
- Used `Optional.of()` in case of `required parameters` in order to match documentation.
**Testing**
- Added `removeStringApprovalsTest` and refactored `deleteTranslationsTest` to ensure correct functionality.
- Updated the `request mock builders` for the …

feat: Add support to Remove String Approvals endpoint

---

src/main/java/com/crowdin/client/teams/TeamsApi.java
src/main/java/com/crowdin/client/teams/model/GroupTeam.java
src/main/java/com/crowdin/client/teams/model/GroupTeamResponseList.java
src/main/java/com/crowdin/client/teams/model/GroupTeamResponseObject.java
src/main/java/com/crowdin/client/users/UsersApi.java
src/main/java/com/crowdin/client/users/model/GroupManager.java
src/main/java/com/crowdin/client/users/model/GroupManagerResponseList.java
src/main/java/com/crowdin/client/users/model/GroupManagerResponseObject.java
src/test/java/com/crowdin/client/teams/TeamsApiTest.java
src/test/java/com/crowdin/client/users/UsersApiTest.java
src/test/resources/api/teams/editGroupTeams.json
src/test/resources/api/teams/groupTeam.json
src/test/resources/api/teams/listGroupTeams.json
src/test/resources/api/users/editGroupManagers.json
src/test/resources/api/users/groupManager.json
src/test/resources/api/users/listGroupManagers.json

<details><summary>Summary</summary>
<p>
This introduces support for managing group managers and teams in the application.
</p>
</details> 
Targets: [issue#312](https://github.com/crowdin/crowdin-api-client-java/issues/312)
- Added models for `GroupManager` and `GroupTeam`, including response handling models (`GroupManagerResponseList`, `GroupTeamResponseList`, `...`).
- Implemented endpoints to `list`, `update`, and `retrieve` group managers and teams.
- Added unit tests to verify the functionality of new endpoints.
- Included mock server data for API responses to ensure correctness.
- Mock data was added to test the newly API use cases like `listing`, `retrieving`, and `updating` group teams and managers.
- All tests passed successfully.
- New classes (e.g. `GroupTeam`) were created …

feat: add support for group managers and teams
