src/main/java/com/crowdin/client/translations/model/ProjectBuild.java
src/test/resources/api/translations/listProjectBuilds.json
src/test/resources/api/translations/projectBuildStatus.json

fix: change ProjectBuild response

---

README.md
build.gradle
src/main/java/com/crowdin/client/projectsgroups/model/ProjectSettings.java

- add `inContextPseudoLanguage` field

Update project model

---

README.md
build.gradle
src/main/java/com/crowdin/client/Sandbox.java

Version 1.2.10 - Fix

---

README.md
build.gradle
src/main/java/com/crowdin/client/sourcefiles/model/XmlFileImportOptions.java
src/main/java/com/crowdin/client/sourcestrings/model/AddSourceStringRequest.java
src/main/java/com/crowdin/client/tasks/model/Task.java
src/main/java/com/crowdin/client/tasks/model/TranslateProgress.java
src/test/java/com/crowdin/client/sourcestrings/SourceStringsApiTest.java
src/test/java/com/crowdin/client/tasks/TasksApiTest.java
src/test/resources/api/strings/addStringRequest.json
src/test/resources/api/tasks/task.json

- 'Add String' request - add `labelIds` parameter
- 'Get Task' response - add `translateProgress` field
- Source Files API - XML File Import Options - add `customSegmentation` field

API updates:

---

src/main/java/com/crowdin/client/workflows/WorkflowsApi.java
src/test/java/com/crowdin/client/workflows/WorkflowsApiTest.java

Removed limit and offset parameters from the listWorkFlowSteps method in WorkflowsApi.java along with the corresponding unit test.

Removal of limit and offset params in listWorkFlowSteps method

---

src/main/java/com/crowdin/client/sourcestrings/model/SourceString.java
src/test/java/com/crowdin/client/sourcestrings/SourceStringsApiTest.java

Closes: #81 
Updated SourceString model to include masterStringId and isDuplicate fields.

81: update SourceString model

---

README.md
build.gradle

- Updated SourceString model to include masterStringId and isDuplicate fields (#86)
- Fix 'Add Tag' response processing (#92)

Version 1.3.20

---

README.md
build.gradle
src/main/java/com/crowdin/client/translations/model/CrowdinTranslationCraeteProjectPseudoBuildForm.java
src/test/java/com/crowdin/client/translations/TranslationsApiTest.java
src/test/resources/api/translations/pseudoBuildProjectRequest.json

Support branchId for CrowdinTranslationCraeteProjectPseudoBuildForm

---

README.md
build.gradle
src/main/java/com/crowdin/client/translations/model/BuildProjectDirectoryTranslationRequest.java
src/main/java/com/crowdin/client/translations/model/BuildProjectFileTranslationRequest.java
src/main/java/com/crowdin/client/translations/model/CrowdinTranslationCreateProjectBuildForm.java
src/main/java/com/crowdin/client/translations/model/ExportProjectTranslationRequest.java
src/main/java/com/crowdin/client/translations/model/ProjectBuild.java

//todo: add unit tests of this new option

support for exportStringsThatPassedWorkflow option

---

src/main/java/com/crowdin/client/users/UsersApi.java
src/main/java/com/crowdin/client/users/model/InviteUserRequest.java
src/test/java/com/crowdin/client/users/UsersApiTest.java
src/test/resources/api/users/editUser.json
src/test/resources/api/users/invitedUser.json

Created below Enterprise User Management Endpoints with test coverage.
- Invite User
- Delete User
- Edit User

Added endpoints for Enterprise User Management

---

src/main/java/com/crowdin/client/distributions/model/AddDistributionRequest.java
src/main/java/com/crowdin/client/distributions/model/Distribution.java
src/main/java/com/crowdin/client/distributions/model/ExportMode.java
src/main/java/com/crowdin/client/reports/ReportsApi.java
src/test/java/com/crowdin/client/distributions/DistributionsApiTest.java
src/test/resources/api/distributions/addDistribution.json
src/test/resources/api/distributions/distribution.json

Also removed redundant spaces from reports api

updated request and response for post distribution api

---

build.gradle

Updated dependency versions in build.gradle and project version.

Updated dependency versions and project version

---

src/main/java/com/crowdin/client/translationmemory/model/TranslationMemory.java
src/test/resources/api/translationmemory/listTms.json
src/test/resources/api/translationmemory/tm.json

Remove deprecated defaultProjectId, add defaultProjectIds properties

---

src/main/java/com/crowdin/client/bundles/BundlesApi.java
src/main/java/com/crowdin/client/bundles/model/Bundle.java
src/test/java/com/crowdin/client/bundles/BundlesApiTest.java
src/test/resources/api/bundles/addBundleRequest.json
src/test/resources/api/bundles/bundle.json
src/test/resources/api/bundles/listBundlesResponse.json

Closes: [Issue#134](https://github.com/crowdin/crowdin-api-client-java/issues/134)

Add isMultilingual missing flag to BundlesApi along with relevant tests.

---

src/main/java/com/crowdin/client/tasks/model/CrowdinTaskCreateFormRequest.java
src/main/java/com/crowdin/client/tasks/model/CrowdinVendorManualTaskCreateFormRequest.java
src/main/java/com/crowdin/client/tasks/model/CrowdinVendorOhtTaskCreateFormRequest.java
src/main/java/com/crowdin/client/tasks/model/EnterpriseTaskCreateFormRequest.java
src/test/java/com/crowdin/client/tasks/TasksApiTest.java
src/test/resources/api/tasks/CrowdinTaskCreateFormRequest.json
src/test/resources/api/tasks/EnterpriseTaskCreateFormRequest.json

feat(api): tasks: add "includePreTranslatedStringsOnly" param

---

src/main/java/com/crowdin/client/projectsgroups/model/EnterpriseProjectRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/FilesBasedProjectRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/ProjectSettings.java
src/main/java/com/crowdin/client/projectsgroups/model/QaCheckCategories.java
src/main/java/com/crowdin/client/projectsgroups/model/StringsBasedProjectRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/TmPenalties.java
src/main/java/com/crowdin/client/projectsgroups/model/TmPriority.java
src/main/java/com/crowdin/client/projectsgroups/model/TmTimeElapsed.java
src/test/java/com/crowdin/client/projectsgroups/ProjectsGroupsApiTest.java
src/test/resources/api/projectsgroups/addProjectRequest.json
src/test/resources/api/projectsgroups/editProject.json
src/test/resources/api/projectsgroups/project.json
src/test/resources/api/projectsgroups/projectSettings.json

\+ add more fields to QaCheckCategories and QaChecksIgnorableCategories
Closes #137

feat(api): add qaChecksIgnorableCategories + TmPenalty + integration

---

src/main/java/com/crowdin/client/reports/ReportsApi.java
src/main/java/com/crowdin/client/reports/model/BaseRatesForm.java
src/main/java/com/crowdin/client/reports/model/CostEstimateFuzzyModeGenerateReportRequest.java
src/main/java/com/crowdin/client/reports/model/CostEstimateGenerateReportRequest.java
src/main/java/com/crowdin/client/reports/model/CostEstimationPostEditingGenerateReportRequest.java
src/main/java/com/crowdin/client/reports/model/GenerateGroupReportRequest.java
src/main/java/com/crowdin/client/reports/model/GroupReportStatus.java
src/main/java/com/crowdin/client/reports/model/GroupReportStatusResponseObject.java
src/main/java/com/crowdin/client/reports/model/GroupTopMembersGenerateGroupReportRequest.java
src/main/java/com/crowdin/client/reports/model/GroupTranslationCostsPostEditingGenerateGroupReportRequest.java
src/main/java/com/crowdin/client/reports/model/GroupingParameter.java
src/main/java/com/crowdin/client/reports/model/LabelIncludeType.java
src/main/java/com/crowdin/client/reports/model/Match.java
src/main/java/com/crowdin/client/reports/model/MatchType.java
src/main/java/com/crowdin/client/reports/model/TranslationCostFuzzyModeGenerateReportRequest.java
src/main/java/com/crowdin/client/reports/model/TranslationCostGenerateReportRequest.java
src/test/java/com/crowdin/client/reports/GroupReportsApiTest.java
src/test/resources/api/reports/generateGroupReportRequest.json
src/test/resources/api/reports/generateOrganizationReportRequest.json
src/test/resources/api/reports/groupReportStatusResponse.json

feat(api): Reports API changes

---

src/test/java/com/crowdin/client/tasks/TasksApiTest.java
src/test/resources/api/tasks/listTasks.json
src/test/resources/api/tasks/task.json

Refs. #194 
Add coverage for Assignee, AssignedTeam model classes

test(tasks): add coverage for tasks/model

---

src/main/java/com/crowdin/client/core/http/impl/json/JacksonJsonTransformer.java
src/main/java/com/crowdin/client/core/http/impl/json/StringsExporterSettingsDeserializer.java
src/main/java/com/crowdin/client/projectsgroups/ProjectsGroupsApi.java
src/main/java/com/crowdin/client/projectsgroups/model/AndroidStringsExporterSettings.java
src/main/java/com/crowdin/client/projectsgroups/model/AndroidStringsExporterSettingsRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/MacOSXStringsExporterSettings.java
src/main/java/com/crowdin/client/projectsgroups/model/MacOSXStringsExporterSettingsRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/StringsExporterSettings.java
src/main/java/com/crowdin/client/projectsgroups/model/StringsExporterSettingsRequest.java
src/main/java/com/crowdin/client/projectsgroups/model/StringsExporterSettingsResource.java
src/main/java/com/crowdin/client/projectsgroups/model/StringsExporterSettingsResponseList.java
src/main/java/com/crowdin/client/projectsgroups/model/StringsExporterSettingsResponseObject.java
src/main/java/com/crowdin/client/projectsgroups/model/XliffStringsExporterSettings.java
src/main/java/com/crowdin/client/projectsgroups/model/XliffStringsExporterSettingsRequest.java
src/test/java/com/crowdin/client/projectsgroups/ProjectStringsExporterSettingsApiTest.java
src/test/resources/api/projectsgroups/stringsexportersettings/addSettingsRequest.json
src/test/resources/api/projectsgroups/stringsexportersettings/editSettingsRequest.json
src/test/resources/api/projectsgroups/stringsexportersettings/list.json
src/test/resources/api/projectsgroups/stringsexportersettings/single.json

feat(api): add Strings Exporter Settings API

---

src/main/java/com/crowdin/client/stringtranslations/StringTranslationsApi.java
src/test/java/com/crowdin/client/stringtranslations/StringTranslationsApiTest.java

Add new parameters (labelIds and excludeLabelIds) for String Translation APIs, and update tests.
Refs: #207

feat: add new parameters support for String Translations APIs

---

src/main/java/com/crowdin/client/screenshots/model/AddScreenshotRequest.java
src/main/java/com/crowdin/client/screenshots/model/Screenshot.java
src/test/java/com/crowdin/client/screenshots/ScreenshotsApiTest.java
src/test/resources/api/screenshots/addScreenshotRequest.json
src/test/resources/api/screenshots/editScreenshot.json
src/test/resources/api/screenshots/listScreenshots.json
src/test/resources/api/screenshots/screenshot.json

feat: Add support for new parameter (labelIds) in Screenshots Api - Issue #213

---

src/main/java/com/crowdin/client/ai/AIApi.java
src/main/java/com/crowdin/client/ai/model/AiProvider.java
src/main/java/com/crowdin/client/ai/model/AiProviderModel.java
src/main/java/com/crowdin/client/ai/model/AiProviderModelResponseList.java
src/main/java/com/crowdin/client/ai/model/AiProviderModelResponseObject.java
src/main/java/com/crowdin/client/ai/model/AiProviderRequest.java
src/main/java/com/crowdin/client/ai/model/AiProviderResponseList.java
src/main/java/com/crowdin/client/ai/model/AiProviderResponseObject.java
src/main/java/com/crowdin/client/ai/model/Config.java
src/main/java/com/crowdin/client/ai/model/Credentials.java
src/test/java/com/crowdin/client/ai/AIApiTest.java
src/test/resources/api/ai/addAiProviderRequestObject.json
src/test/resources/api/ai/aiProvidersResponseObject.json
src/test/resources/api/ai/editAiProviderRequest.json
src/test/resources/api/ai/listAiProviderModels.json
src/test/resources/api/ai/listAiProviderResponse.json

Support for https://github.com/crowdin/crowdin-api-client-java/issues/270

feat: Adding APIs for AI Providers

---

src/main/java/com/crowdin/client/ai/AIApi.java
src/main/java/com/crowdin/client/ai/model/AiReportAttributes.java
src/main/java/com/crowdin/client/ai/model/AiReportFormat.java
src/main/java/com/crowdin/client/ai/model/AiReportGenerate.java
src/main/java/com/crowdin/client/ai/model/AiReportGenerateResponse.java
src/main/java/com/crowdin/client/ai/model/GenerateAiReportRequest.java
src/main/java/com/crowdin/client/ai/model/GenerateAiReportRequestSchema.java
src/main/java/com/crowdin/client/core/http/impl/json/JacksonJsonTransformer.java
src/test/java/com/crowdin/client/ai/AIApiTest.java
src/test/java/com/crowdin/client/framework/TestHttpClient.java
src/test/resources/api/ai/checkAiReportGenerationStatusResponse.json
src/test/resources/api/ai/downloadAiReportResponse.json
src/test/resources/api/ai/generateAiReportRequest.json
src/test/resources/api/ai/generateAiReportResponse.json

feat: add AI report methods
